---
language: python

python:
  - "3.7"

services:
  - docker

env:
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-centos-systemd"
    - image="docker-redhat-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - image="docker-opensuse-systemd"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "n7u1Uc3sZszghMynczG25+WGHDctpTRgXNpL7VDbj0ehoPQf1e0gNvXh2oQJhjssqfCgSPzdKhbF+X0/TJL2CLIZaMJXzlnQNek1AbpKfAfzmAAk8xCshAvUvto/sP/LKUCUY6dRVUS154p5p9h7RIYVPkBLqvTM0OdOizo6LzJTiqHPd0IwwsUMj6xAms6hwlY1m3M0q1GCx9R+DsqNxKWXR8mEBgvDap+KLxrGT34dOjUZqVqUA7qflbQpLrDsEG6ZR9UIXxOoQoyqwKqXG66FJfKRrMLnxLbi7UC9HBl4Dda0PZIyWbVhotM/vK/8SW72YyR+bqvqBmunPwaU5p15ipArGpMkRTm642RyeKB4XvgCvIBBycC/kl5aj2DBumkGs+nqZpq1fFpK2clSVUHdmkffAddbjRrMH9ZMnWfP85KaHXkg6cymBFxpp+K0uRL6QFTqPO/tHmZ+oWtiKUvy25n06KiDkMdn4MsqfvpaB5CfidbC7zcKMcGk5lcWwvKLMsBKXZI48z7ty/8XKYO1Ss/XgEyPbXg4MrSTwPCY/0tawaAdqqMen+0qLfSURsFN5TG0+Ym/ov+rLqq3TaqyawSRMAe9p1atWKkE3lEbS45KLuvlEMS9W1XHrzrx5MuDcFFqii8ePI7FFeMWoSFqeYXT0Bk7K3FlQ/vyf28="
  email: false
