---
# tasks file for molecule

- name: Install requirements
  ansible.builtin.package:
    name: "{{ molecule_requirements }}"
  become: yes
  become_user: root

- name: Install molecule (pip)
  ansible.builtin.pip:
    name: molecule
    extra_args: "{{ molecule_extra_args | default(omit) }}"

# - name: Install ansible-core (pip)
#   ansible.builtin.pip:
#     name: ansible-core
#     extra_args: "{{ molecule_extra_args | default(omit) }}"

- name: Install molecule-plugins (pip)
  ansible.builtin.pip:
    name: "{{ molecule_plugins }}"
    extra_args: "{{ molecule_extra_args | default(omit) }}"
