---
# tasks file for molecule

- name: Install requirements
  ansible.builtin.package:
    name: "{{ molecule_requirements }}"
  become: yes
  become_user: root

- name: Install molecule (pip)
  ansible.builtin.pip:
    name: molecule[ansible-core,docker,lint]
    extra_args: "{{ molecule_extra_args | default(omit) }}"
  when:
    - ansible_os_family != "Debian"

- name: Install molecule (package)
  ansible.builtin.package:
    name: python3-molecule
  when:
    - ansible_os_family == "Debian"
