---
# tasks file for molecule

- name: install requirements
  ansible.builtin.package:
    name: "{{ molecule_requirements }}"
    state: present
  become: yes

- name: install molecule
  ansible.builtin.pip:
    name: molecule[ansible-base,docker,lint]
    state: present
    extra_args: "{{ molecule_extra_args | default(omit) }}"
