---
# tasks file for molecule
- name: test veriables and environment
  assert:
    that:

- name: install requirements
  package:
    name: "{{ molecule_requirements }}"
    state: present
  register: molecule_install_requirements
  until: molecule_install_requirements is succeeded
  retries: 3

- name: install molecule
  pip:
    name: "{{ molecule_packages }}"
    state: present
    # extra_args: "--ignore-installed PyYAML"
  register: molecule_install_molecule
  until: molecule_install_molecule is succeeded
  retries: 3
