---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check if molecule returns a version
      ansible.builtin.command:
        cmd: molecule --version
      environment:
        PATH: "/bin:/usr/bin:/usr/local/bin"
